import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    // General
    language: 'Language',
    admin: 'Admin',
    dashboard: 'Dashboard',
    myProfile: 'My Profile',
    logout: 'Logout',
    login: 'Login',
    getStarted: 'Get Started',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    search: 'Search',
    loading: 'Loading...',
    saving: 'Saving...',
    noData: 'No data available',

    // Auth
    welcomeBack: 'Welcome Back',
    signInAccount: 'Sign in to your account',
    usernameOrEmail: 'Username or Email',
    enterUsernameOrEmail: 'Enter username or email',
    password: 'Password',
    enterPassword: 'Enter password',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    createOne: 'Create one',
    demoAccount: 'Demo account',
    createAccount: 'Create Account',
    setupProfile: 'Set up your bio link profile in seconds',
    username: 'Username',
    profileUrlHelp: 'This will be your profile URL:',
    email: 'Email',
    minimumPassword: 'Minimum 6 characters',
    creatingAccount: 'Creating account...',
    alreadyAccount: 'Already have an account?',
    pleaseFill: 'Please fill in all fields',
    passwordMin: 'Password must be at least 6 characters',
    accountCreated: 'Account created! Welcome to BioPlatform',
    registrationFailed: 'Registration failed',
    welcomeToast: 'Welcome back!',
    loginFailed: 'Login failed',

    // Dashboard
    manageProfile: 'Manage your profile and links',
    copyUrl: 'Copy URL',
    preview: 'Preview',
    profile: 'Profile',
    links: 'Links',
    theme: 'Theme',
    stats: 'Stats',
    addLink: 'Add Link',
    quickAddSocial: 'Quick Add Social',
    quickAddSocialLinks: 'Quick Add Social Links',
    fullLink: 'Full Link',
    add: 'Add',
    discordNick: 'Discord Nick',

    // Profile Tab
    profileInfo: 'Profile Info',
    displayName: 'Display Name',
    yourName: 'Your Name',
    bio: 'Bio',
    bioPlaceholder: 'Tell the world about yourself...',
    avatarUrl: 'Avatar URL',
    location: 'Location',
    locationPlaceholder: '🌍 Somewhere',
    backgroundMedia: 'Background & Media',
    backgroundImageUrl: 'Background Image URL',
    backgroundVideoUrl: 'Background Video URL',
    musicUrl: 'Music URL',
    musicTitle: 'Music Title',
    musicArtist: 'Music Artist',
    songName: 'Song Name',
    artist: 'Artist',
    settingsBadges: 'Settings & Badges',
    accentColor: 'Accent Color',
    clickToEnterScreen: 'Click to Enter Screen',
    showViewCount: 'Show View Count',
    enableEffects: 'Enable Effects',
    badges: 'Badges',
    saveProfile: '💾 Save Profile',
    profileSaved: 'Profile saved!',
    failedToSave: 'Failed to save profile',
    failedToLoad: 'Failed to load profile data',

    // Links Tab
    noLinksYet: 'No links yet. Add your first link!',
    featured: 'Featured',
    hidden: 'Hidden',
    hide: 'Hide',
    show: 'Show',
    failedToAddLink: 'Failed to add link',
    failedToUpdateLink: 'Failed to update link',
    failedToDeleteLink: 'Failed to delete link',
    linkAdded: 'Link added!',
    linkUpdated: 'Link updated!',
    linkDeleted: 'Link deleted',
    deleteThisLink: 'Delete this link?',
    failedToggleVisibility: 'Failed to toggle visibility',
    profileUrlCopied: 'Profile URL copied!',

    // Link Editor
    editLink: 'Edit Link',
    addNewLink: 'Add New Link',
    title: 'Title',
    url: 'URL',
    type: 'Type',
    icon: 'Icon',
    color: 'Color',
    visible: 'Visible',
    saveChanges: 'Save Changes',
    normalLink: 'Normal Link',
    socialLink: 'Social Link',
    musicLink: 'Music Link',
    videoLink: 'Video Link',
    contactLink: 'Contact Link',
    customLink: 'Custom Link',

    // Theme Tab
    chooseTheme: 'Choose Theme',
    resetColor: 'Reset Color',
    accentColorReset: 'Accent color reset',
    failedToSaveTheme: 'Failed to save theme',

    // Stats Tab
    totalViews: 'Total Views',
    totalClicks: 'Total Clicks',
    uniqueClickers: 'Unique Clickers',
    totalLinks: 'Total Links',
    mobileClicks: 'Mobile Clicks',
    desktopClicks: 'Desktop Clicks',
    profileUrl: 'Profile URL',
    clicksByDevice: 'Clicks by Device',
    clicksByCountry: 'Clicks by Country',
    topClickedLinks: 'Top Clicked Links',
    recentClicks: 'Recent Clicks',
    time: 'Time',
    link: 'Link',
    ip: 'IP',
    device: 'Device',
    country: 'Country',
    clicks: 'clicks',
    noCountryData: 'No country data yet.',
    noDetailedClicks: 'Detailed click logs will appear after the new migration is applied and new clicks arrive.',
    profileCreated: 'Profile created:',
    lastUpdated: 'Last updated:',
    mobile: 'Mobile',
    tablet: 'Tablet',
    desktop: 'Desktop',
    failedToLoadStats: 'Failed to load stats',
    deletedLink: 'Deleted link',
    unknown: 'Unknown',

    // Admin Panel
    adminPanel: 'Admin Panel',
    managePlatform: 'Manage users, stats, and platform settings.',
    overview: 'Overview',
    users: 'Users',
    visitors: 'Visitors',
    totalUsers: 'Total Users',
    newUsersToday: 'New Users Today',
    totalLoggedVisits: 'Total Logged Visits',
    loggedClicks: 'Logged Clicks',
    searchUsers: 'Search users by username, email, or display name...',
    user: 'User',
    role: 'Role',
    lastLogin: 'Last Login',
    joined: 'Joined',
    actions: 'Actions',
    never: 'Never',
    noUsersFound: 'No users found matching your search.',
    recentVisitors: 'Recent Visitors (Last 100)',
    ipAddress: 'IP Address',
    profileVisited: 'Profile Visited',
    noVisitLogs: 'No visit logs recorded yet.',
    generalUnknown: 'General/Unknown',
    editUser: 'Edit User:',
    displayNameLabel: 'Display Name',
    totalViewsEdit: 'Total Views',
    verifiedAccount: 'Verified Account ✓',
    userUpdated: 'User updated successfully',
    failedUpdateUser: 'Failed to update user',
    userDeleted: 'User deleted',
    failedDeleteUser: 'Failed to delete user',
    confirmDeleteUser: 'Are you absolutely sure? This will delete the user and ALL their data!',
    failedLoadAdmin: 'Failed to load admin data',
    settings: 'Settings',
    platformSettings: 'Platform Settings',
    earlyUserDeadline: 'Early User Badge Deadline',
    earlyUserDeadlineDesc: 'Users who register before this date will automatically receive the Early User badge. After this date, new users will not get it.',
    earlyUserActiveUntil: 'Early User badge active until',
    settingsSaved: 'Settings saved successfully',
    failedSaveSettings: 'Failed to save settings',
    resetPassword: 'Reset Password',
    newPassword: 'New password (min 6 chars)',
    passwordResetSuccess: 'Password reset successfully!',
    failedResetPassword: 'Failed to reset password',
    badgeManagement: 'Badge Management (Admin)',
    userBadges: 'Your Badges',
    systemBadges: 'System Badges',
    adminOnlyBadge: 'Only admin can change this badge',
    adminOnlyBadgeDesc: 'These badges can only be assigned by an administrator.',

    // Landing
    bioLinkPlatform: 'Your bio link platform',
    heroTitle1: 'One Link.',
    heroTitle2: 'Infinite Possibilities.',
    heroDesc: 'Create a stunning, customizable profile page with all your links, social media, music, and more. Share everything about you in one beautiful page.',
    createYourProfile: 'Create Your Profile →',
    viewDemo: 'View Demo',
    everythingYouNeed: 'Everything You Need',
    featuresDesc: 'A complete bio link platform packed with features to make your profile stand out',
    readyToCreate: 'Ready to Create Your Profile?',
    joinNow: 'Join now and get your personalized bio link page in seconds',
    getStartedFree: "Get Started — It's Free",
    signUp: 'Sign Up',

    // Features
    feat1Title: 'Beautiful Templates',
    feat1Desc: '10+ stunning themes from neon to luxury to fit your style',
    feat2Title: 'Link Management',
    feat2Desc: 'Add, edit, and organize all your important links in one place',
    feat3Title: 'Music Player',
    feat3Desc: 'Add background music to your profile for an immersive experience',
    feat4Title: 'Analytics',
    feat4Desc: 'Track profile views, link clicks, and see your top content',
    feat5Title: 'Video Backgrounds',
    feat5Desc: 'Set a looping video background for a premium profile look',
    feat6Title: 'Effects & Badges',
    feat6Desc: 'Glow effects, glass cards, animated gradients, and profile badges',
  },
  tr: {
    // General
    language: 'Dil',
    admin: 'Admin',
    dashboard: 'Panel',
    myProfile: 'Profilim',
    logout: 'Çıkış',
    login: 'Giriş',
    getStarted: 'Başla',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    view: 'Görüntüle',
    search: 'Ara',
    loading: 'Yükleniyor...',
    saving: 'Kaydediliyor...',
    noData: 'Veri bulunamadı',

    // Auth
    welcomeBack: 'Tekrar Hoş Geldin',
    signInAccount: 'Hesabına giriş yap',
    usernameOrEmail: 'Kullanıcı adı veya e-posta',
    enterUsernameOrEmail: 'Kullanıcı adı veya e-posta gir',
    password: 'Şifre',
    enterPassword: 'Şifreni gir',
    signingIn: 'Giriş yapılıyor...',
    signIn: 'Giriş Yap',
    noAccount: 'Hesabın yok mu?',
    createOne: 'Hesap oluştur',
    demoAccount: 'Demo hesap',
    createAccount: 'Hesap Oluştur',
    setupProfile: 'Bio link profilini saniyeler içinde hazırla',
    username: 'Kullanıcı adı',
    profileUrlHelp: 'Profil adresin:',
    email: 'E-posta',
    minimumPassword: 'En az 6 karakter',
    creatingAccount: 'Hesap oluşturuluyor...',
    alreadyAccount: 'Zaten hesabın var mı?',
    pleaseFill: 'Lütfen tüm alanları doldur',
    passwordMin: 'Şifre en az 6 karakter olmalı',
    accountCreated: 'Hesap oluşturuldu! BioPlatforma hoş geldin',
    registrationFailed: 'Kayıt başarısız',
    welcomeToast: 'Tekrar hoş geldin!',
    loginFailed: 'Giriş başarısız',

    // Dashboard
    manageProfile: 'Profilini ve linklerini yönet',
    copyUrl: 'URL Kopyala',
    preview: 'Önizle',
    profile: 'Profil',
    links: 'Linkler',
    theme: 'Tema',
    stats: 'İstatistikler',
    addLink: 'Link Ekle',
    quickAddSocial: 'Hızlı Sosyal Ekle',
    quickAddSocialLinks: 'Sosyal Linkleri Hızlı Ekle',
    fullLink: 'Tam Link',
    add: 'Ekle',
    discordNick: 'Discord Adı',

    // Profile Tab
    profileInfo: 'Profil Bilgileri',
    displayName: 'Görünen Ad',
    yourName: 'Adın',
    bio: 'Hakkında',
    bioPlaceholder: 'Kendini dünyaya anlat...',
    avatarUrl: 'Avatar URL',
    location: 'Konum',
    locationPlaceholder: '🌍 Bir Yer',
    backgroundMedia: 'Arka Plan & Medya',
    backgroundImageUrl: 'Arka Plan Resim URL',
    backgroundVideoUrl: 'Arka Plan Video URL',
    musicUrl: 'Müzik URL',
    musicTitle: 'Müzik Başlığı',
    musicArtist: 'Sanatçı',
    songName: 'Şarkı Adı',
    artist: 'Sanatçı',
    settingsBadges: 'Ayarlar & Rozetler',
    accentColor: 'Vurgu Rengi',
    clickToEnterScreen: 'Giriş Ekranı (Tıkla)',
    showViewCount: 'Görüntülenme Sayısını Göster',
    enableEffects: 'Efektleri Etkinleştir',
    badges: 'Rozetler',
    saveProfile: '💾 Profili Kaydet',
    profileSaved: 'Profil kaydedildi!',
    failedToSave: 'Profil kaydedilemedi',
    failedToLoad: 'Profil verisi yüklenemedi',

    // Links Tab
    noLinksYet: 'Henüz link yok. İlk linkini ekle!',
    featured: 'Öne Çıkan',
    hidden: 'Gizli',
    hide: 'Gizle',
    show: 'Göster',
    failedToAddLink: 'Link eklenemedi',
    failedToUpdateLink: 'Link güncellenemedi',
    failedToDeleteLink: 'Link silinemedi',
    linkAdded: 'Link eklendi!',
    linkUpdated: 'Link güncellendi!',
    linkDeleted: 'Link silindi',
    deleteThisLink: 'Bu link silinsin mi?',
    failedToggleVisibility: 'Görünürlük değiştirilemedi',
    profileUrlCopied: 'Profil URL kopyalandı!',

    // Link Editor
    editLink: 'Linki Düzenle',
    addNewLink: 'Yeni Link Ekle',
    title: 'Başlık',
    url: 'URL',
    type: 'Tür',
    icon: 'İkon',
    color: 'Renk',
    visible: 'Görünür',
    saveChanges: 'Değişiklikleri Kaydet',
    normalLink: 'Normal Link',
    socialLink: 'Sosyal Link',
    musicLink: 'Müzik Linki',
    videoLink: 'Video Linki',
    contactLink: 'İletişim Linki',
    customLink: 'Özel Link',

    // Theme Tab
    chooseTheme: 'Tema Seç',
    resetColor: 'Rengi Sıfırla',
    accentColorReset: 'Vurgu rengi sıfırlandı',
    failedToSaveTheme: 'Tema kaydedilemedi',

    // Stats Tab
    totalViews: 'Toplam Görüntülenme',
    totalClicks: 'Toplam Tıklama',
    uniqueClickers: 'Tekil Tıklayan',
    totalLinks: 'Toplam Link',
    mobileClicks: 'Mobil Tıklama',
    desktopClicks: 'Masaüstü Tıklama',
    profileUrl: 'Profil URL',
    clicksByDevice: 'Cihaza Göre Tıklamalar',
    clicksByCountry: 'Ülkeye Göre Tıklamalar',
    topClickedLinks: 'En Çok Tıklanan Linkler',
    recentClicks: 'Son Tıklamalar',
    time: 'Zaman',
    link: 'Link',
    ip: 'IP',
    device: 'Cihaz',
    country: 'Ülke',
    clicks: 'tıklama',
    noCountryData: 'Henüz ülke verisi yok.',
    noDetailedClicks: 'Yeni göç uygulandıktan ve yeni tıklamalar geldikten sonra detaylı click log\'ları görünecek.',
    profileCreated: 'Profil oluşturuldu:',
    lastUpdated: 'Son güncelleme:',
    mobile: 'Mobil',
    tablet: 'Tablet',
    desktop: 'Masaüstü',
    failedToLoadStats: 'İstatistikler yüklenemedi',
    deletedLink: 'Silinmiş link',
    unknown: 'Bilinmiyor',

    // Admin Panel
    adminPanel: 'Admin Paneli',
    managePlatform: 'Kullanıcıları, istatistikleri ve platform ayarlarını yönet.',
    overview: 'Genel Bakış',
    users: 'Kullanıcılar',
    visitors: 'Ziyaretçiler',
    totalUsers: 'Toplam Kullanıcı',
    newUsersToday: 'Bugün Yeni Kullanıcı',
    totalLoggedVisits: 'Toplam Kayıtlı Ziyaret',
    loggedClicks: 'Kayıtlı Tıklama',
    searchUsers: 'Kullanıcı adı, e-posta veya görünen ada göre ara...',
    user: 'Kullanıcı',
    role: 'Rol',
    lastLogin: 'Son Giriş',
    joined: 'Katıldı',
    actions: 'İşlemler',
    never: 'Hiç',
    noUsersFound: 'Aramanızla eşleşen kullanıcı bulunamadı.',
    recentVisitors: 'Son Ziyaretçiler (Son 100)',
    ipAddress: 'IP Adresi',
    profileVisited: 'Ziyaret Edilen Profil',
    noVisitLogs: 'Henüz ziyaret kaydı yok.',
    generalUnknown: 'Genel/Bilinmiyor',
    editUser: 'Kullanıcıyı Düzenle:',
    displayNameLabel: 'Görünen Ad',
    totalViewsEdit: 'Toplam Görüntülenme',
    verifiedAccount: 'Doğrulanmış Hesap ✓',
    userUpdated: 'Kullanıcı başarıyla güncellendi',
    failedUpdateUser: 'Kullanıcı güncellenemedi',
    userDeleted: 'Kullanıcı silindi',
    failedDeleteUser: 'Kullanıcı silinemedi',
    confirmDeleteUser: 'Emin misin? Bu işlem kullanıcıyı ve TÜM verilerini silecek!',
    failedLoadAdmin: 'Admin verisi yüklenemedi',
    settings: 'Ayarlar',
    platformSettings: 'Platform Ayarları',
    earlyUserDeadline: 'Erken Kullanıcı Rozeti Son Tarihi',
    earlyUserDeadlineDesc: 'Bu tarihten önce kayıt olan kullanıcılar otomatik olarak Erken Kullanıcı rozetini alacak. Bu tarihten sonra yeni kullanıcılar rozeti almayacak.',
    earlyUserActiveUntil: 'Erken Kullanıcı rozeti aktif bitiş',
    settingsSaved: 'Ayarlar başarıyla kaydedildi',
    failedSaveSettings: 'Ayarlar kaydedilemedi',
    resetPassword: 'Şifre Sıfırla',
    newPassword: 'Yeni şifre (min 6 karakter)',
    passwordResetSuccess: 'Şifre başarıyla sıfırlandı!',
    failedResetPassword: 'Şifre sıfırlanamadı',
    badgeManagement: 'Rozet Yönetimi (Admin)',
    userBadges: 'Rozetleriniz',
    systemBadges: 'Sistem Rozetleri',
    adminOnlyBadge: 'Bu rozeti yalnızca admin değiştirebilir',
    adminOnlyBadgeDesc: 'Bu rozetler yalnızca bir yönetici tarafından atanabilir.',

    // Landing
    bioLinkPlatform: 'Bio link platformun',
    heroTitle1: 'Tek Link.',
    heroTitle2: 'Sonsuz Olasılıklar.',
    heroDesc: 'Tüm linklerini, sosyal medyanı, müziğini ve daha fazlasını içeren göz alıcı, özelleştirilebilir bir profil sayfası oluştur. Her şeyini tek bir güzel sayfada paylaş.',
    createYourProfile: 'Profilini Oluştur →',
    viewDemo: 'Demoyu Gör',
    everythingYouNeed: 'İhtiyacın Olan Her Şey',
    featuresDesc: 'Profilini öne çıkarmak için özelliklerle dolu eksiksiz bir bio link platformu',
    readyToCreate: 'Profilini Oluşturmaya Hazır mısın?',
    joinNow: 'Hemen katıl ve kişisel bio link sayfanı saniyeler içinde al',
    getStartedFree: 'Başla — Ücretsiz',
    signUp: 'Kayıt Ol',

    // Features
    feat1Title: 'Güzel Temalar',
    feat1Desc: 'Stiline uyan neondan lükse 10+ çarpıcı tema',
    feat2Title: 'Link Yönetimi',
    feat2Desc: 'Tüm önemli linklerini tek bir yerde ekle, düzenle ve organize et',
    feat3Title: 'Müzik Çalar',
    feat3Desc: 'Sürükleyici bir deneyim için profiline arka plan müziği ekle',
    feat4Title: 'Analitik',
    feat4Desc: 'Profil görüntülemelerini, link tıklamalarını takip et ve en iyi içeriğini gör',
    feat5Title: 'Video Arka Planlar',
    feat5Desc: 'Premium bir profil görünümü için döngüsel video arka plan ayarla',
    feat6Title: 'Efektler & Rozetler',
    feat6Desc: 'Glow efektleri, cam kartlar, animasyonlu degradeler ve profil rozetleri',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('bio_language') || 'en');

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage(nextLanguage) {
      const safeLanguage = nextLanguage === 'tr' ? 'tr' : 'en';
      localStorage.setItem('bio_language', safeLanguage);
      setLanguage(safeLanguage);
      document.documentElement.lang = safeLanguage;
    },
    t(key) {
      return translations[language]?.[key] || translations.en[key] || key;
    },
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
}
